<?php

$title = 'Изменение пароля';
/** @var Zend\View\Renderer\PhpRenderer $this */
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<form class="form-horizontal" method="post">

    <?php echo $this->formRowHelper($form->get('password_old')); ?>
    <?php echo $this->formRowHelper($form->get('password')); ?>
    <?php echo $this->formRowHelper($form->get('password_confirm')); ?>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Сохранить</button>
            <a href="<?= $this->url('user/profile', array('controller' => 'profile', 'action' => 'index')) ?>"
               class="btn btn-default">Отмена</a>
        </div>
    </div>
</form>