<?php
use Auth\Form\Login;
use Zend\Form\View\Helper\Form;

/** @var \Zend\Form\Element\Captcha $captcha */

$title = 'Аутентификация';
/** @var Zend\View\Renderer\PhpRenderer $this */
$this->headTitle($title);

/** @var Login $form */
$loginMessages = $form->get('login')->getMessages();
$pwdMessages = $form->get('pwd')->getMessages();
$captchaMessages = $form->get('captcha')->getMessages();

?>
<div id="authentication" class="content">
	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<?php if($err_message):?>
		<div><?=$err_message?></div>
	<?php endif;?>

	<form class="form-horizontal" method="post" action="<?= $this->url('login') ?>">
		<div class="form-group<?= ($loginMessages ? ' has-error' : '') ?>">
			<label for="inputLogin" class="col-sm-2 control-label">Логин</label>
			<div class="col-sm-10">
				<input type="text" name="login" class="form-control" id="inputLogin" value="<?= $form->get('login')->getValue() ?>" placeholder="логин">
				<p class="help-block help-block-error">
					<?= array_shift($loginMessages) ?>
				</p>
			</div>
		</div>

		<!--		--><?php //echo $this->formRow($form->get('login')); ?>

		<div class="form-group<?= ($pwdMessages ? ' has-error' : '') ?>">
			<label for="inputPwd" class="col-sm-2 control-label">Пароль</label>
			<div class="col-sm-10">
				<input type="password" name="pwd" class="form-control" id="inputPwd" value="<?= $form->get('pwd')->getValue() ?>" placeholder="пароль">
				<p class="help-block help-block-error">
					<?= array_shift($pwdMessages) ?>
				</p>
			</div>
		</div>

		<!--	--><?php //echo $this->formRow($form->get('pwd')); ?>

		<div class="form-group">
			<?php $captcha = $form->get('captcha'); ?>
			<label for="inputCaptcha" class="col-sm-12"><?= $captcha->getOption('label'); ?></label>
			<div class="clear"></div>
			<div class="col-sm-12 captcha">
				<?= $this->formCaptcha($captcha); ?>
				<p class="help-block help-block-error<?= ($captchaMessages ? ' has-error' : '') ?>">
					<?= $this->formElementErrors($captcha); ?>
				</p>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-default">Войти</button>
			</div>
		</div>
	</form>
</div>