<?php

$title = 'Разрешенные списки';
/** @var Zend\View\Renderer\PhpRenderer $this */
$this->headTitle($title);

/** @var array $domains */

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if ($message): ?>
	<div><?= $message ?></div>
<?php endif; ?>
<!--<form action="" class="form-horizontal" method="post">-->

<div class="row">
	<div class="col-lg-2 col-md-2 col-sm-2">
		<a href="/lists/white-list/create" class="btn btn-default">Добавить домен</a>
	</div>
	<div class="col-lg-2 col-md-2 col-sm-2">
		<a href="/lists/white-list/import" class="btn btn-default">Импортировать из файла</a>
	</div>
</div>

<form method="post" action="/lists/white-list/remove">
	<table class="table table-striped">
		<thead>
		<tr>
			<th></th>
			<th>Дата добавления</th>
			<th>Домен</th>
			<th>Описание</th>
		</tr>
		</thead>

		<tbody>
		<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $item) { ?>
				<tr>
					<td width="80">
						<input type="checkbox" name="domains[]" value="<?= $item['er_id'] ?>" />
						<a href="<?= $this->url('lists', ['controller' => 'white-list', 'action' => 'update', 'id' => $item['er_id']]) ?>" >
							<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
						</a>
						<a href="<?= $this->url('lists', ['controller' => 'white-list', 'action' => 'removeOne', 'id' => $item['er_id']]) ?>" >
							<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
						</a>
					</td>
					<td><?= date('d.m.Y', strtotime($item['created'])) ?></td>
					<td><?= $this->escapeHtml($item['resource']) ?></td>
					<td><?= $this->escapeHtml($item['description']) ?></td>
				</tr>
			<?php } ?>

		<?php endif; ?>
		</tbody>

	</table>

	<button type="submit" class="btn btn-default">Удалить выбранные</button>
</form>
<?php echo $this->paginationControl($this->paginator, 'Sliding', null, array('route' => ['lists/white-list', 'white-list'])); ?>


<!--</form>-->