<?php

$title = 'Импорт доменов';
/** @var Zend\View\Renderer\PhpRenderer $this */
$this->headTitle($title);

$file = $form->get('file');
$errors = $file->getMessages();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<form class="form-horizontal" method="post" enctype="multipart/form-data">

	<div class="form-group">
		<label for="inputFile" class="col-sm-2 control-label"><?= $file->getOption('label'); ?></label>
		<div class="col-sm-10">
			<?= $this->formFile($file); ?>
			<p class="help-block help-block-error<?= ($errors ? ' has-error' : '') ?>">
				<?= $this->formElementErrors($file); ?>
			</p>
		</div>
	</div>

	<div class="col-sm-10">
		<?php echo $this->formRow($form->get('submit')); ?>
	</div>

</form>