<?php

$title = 'Редактирование черного списка';
/** @var Zend\View\Renderer\PhpRenderer $this */
$this->headTitle($title);

/** @var string $domain */
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<form class="form-horizontal" method="post">

	<div class="form-group">
		<?php echo $this->formRow($form->get('resource')); ?>
	</div>

	<div class="form-group">
		<?php echo $this->formRow($form->get('description')); ?>
	</div>

	<div class="col-sm-10">
		<?php echo $this->formRow($form->get('submit')); ?>
	</div>

	<div class="col-sm-10">
		<a href="<?= $this->url('lists', ['controller' => 'black-list', 'action' => 'remove', 'id' => $er_id]) ?>" class="btn btn-default">Удалить</a>
	</div>

</form>
